auth:
  rootPassword: securepassword
  database: e-marketplace
  username: app
  password: apppassword
primary:
  persistence:
    enabled: false
    existingClaim: mysql-pvc
  containerSecurityContext:
    enabled: false
volumePermissions:
  enabled: false