mysql: #this is for placing for dependencies value based on Chart.yaml
  auth:
    rootPassword: securepassword
    database: e-marketplace
    username: app
    password: apppassword
  primary:
    persistence:
      enabled: true
      existingClaim: mysql-pvc
    containerSecurityContext:
      enabled: false
  volumePermissions:
    enabled: true