auth:
  rootPassword: securepassword
  database: e-marketplace
  username: app
  password: apppassword
primary:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
    runAsNonRoot: false
secondary:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
    runAsNonRoot: false
volumePermissions:
  enabled: true