apiVersion: v1
kind: Service
metadata:
  name: e-marketplace-db
  namespace: e-marketplace
spec:
  ports:
  - name: http
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql
    tier: backend
    layer: database
