apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pv-source-code-e-marketplace-claim
    namespace: e-marketplace
spec:
    storageClassName: standard
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi