apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: e-marketplace-db
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/devops-warrior-team/e-marketplace-infra-repo.git
    targetRevision: HEAD
    path: e-marketplace-db/kubernetes-manifest
  destination: 
    server: https://kubernetes.default.svc
    namespace: e-marketplace

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true